### ISSUE TITLE
GitHub API Token Permissions

### ISSUE THREAD

**Issue by burrrata** [aracred/bot#10]
> @Evalir many questions

# README

### GitHub API Token Permissions
The [README describes a GitHub API Token](https://github.com/aracred/bot#configuration).

What permissions does the `GITHUB_API_TOKEN` require?

### Running Locally

If we have `.env.sample` configured correctly, can we run `npm run dev` locally to have the bot work on Discord as long as it's running on our computer, or does it have to be deployed to Heroku? (tried running locally and nothing happened)

# .env.sample

### YOUR_SENTRY_DSN

What is this and what is it for? Is it required or can it be ignored?

### Whitelisted Channels

Is there a way to set these all to be good to go by default?

**Comment by Evalir** [comment]
Only the `YOUR_SENTRY_DSN` can be ignored, as this is information for developers. As for whitelisted channels,  If you leave an empty string on the config var, it will read all channels.

**Comment by burrrata** [comment]
Resolved and incorporated into the [AraCred Deployment Guide](https://aracred.github.io/website/docs/deploymentOverview/)
